### ISSUE TITLE
Box Drive Log-in not working

### ISSUE THREAD

**Issue by JeffreyMai** [charconst/homebank_flurry_frontend#12]
I've been trying to relog into my Box Drive with the @g.ucla.edu email but Box doesn't register that the account is there. Claims password is incorrect even though I am sure it's the right one. Not sure if anyone else has ran into this problem but would much appreciate some advice on this.

**Comment by AnneSWarlaumont** [comment]
Gonna close this because the message is not about HomeBank Flurry ( I also just sent you an email about where to post the issue instead). Thanks!
