### ISSUE TITLE
"Next Clip" button frozen near end of task

### ISSUE THREAD

**Issue by sscanlan21** [charconst/homebank_flurry_frontend#8]
Hi! I am very close to the end of my current file (0530_000304), at the 15:26:19 mark to be exact, and the "next clip" button is not filling in green to allow me to click it and go to the next clip. My first thought is that it could be the last clip of the file and so there is no next clip to move on to. I have tried signing out and signing back in as well as clicking the replay button several times and waiting awhile after selecting the number rating to see if it turns green. Do you have any other suggestions as to what may be the issue/things I could try to fix it? Thank you!

**Comment by charconst** [comment]
HI there! Thanks for reporting this--I'll investigate and get back to you.

**Comment by charconst** [comment]
Hi Sophie - so the next button should only be disabled if you haven't been able to rate a clip. I looked through the server logs and it was throwing an error relating to our database which means your rating wasn't able to get submitted and thus the next button wasn't turning green. 

ERROR: Error: 3 INVALID_ARGUMENT: too many index entries for entity

I'll need to figure out why that's happening and push a fix. In the meantime, maybe move onto a different clip?

**Comment by sscanlan21** [comment]
Ok sounds good, thank you!

**Comment by charconst** [comment]
@sscanlan21 Hi Sophie - I pushed a fix to our backend that should resolve the issue. Let me know if that works and you're able to move onto the next clip. Thanks!

**Comment by sscanlan21** [comment]
Hi Charlie, it worked! Thank you!!

**Comment by sscanlan21** [comment]
I should also add in case this issue pops up again for someone else that I had to sign out and sign back in again for it to work
