### ISSUE TITLE
Network Error / Unable to log in to access homebank

### ISSUE THREAD

**Issue by Makkuho** [charconst/homebank_flurry_frontend#9]
I was trying to log into HomeBank to access the files but I keep running into a Network Error. Tried connecting to VPN and trying again but run into the same issue.

**Comment by charconst** [comment]
@Makkuho Server is undergoing maintenance as we migrate some of our database data. Will let you know when it's back up.

**Comment by charconst** [comment]
@Makkuho Server is now up again. Let me know if you run into any issues.
